/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vacinarMe;

import javax.swing.JOptionPane;

/**
 *
 * @author Jhonatans
 */
public class TealLogin extends javax.swing.JFrame {

    /**
     * Creates new form TealLogin
     */
    public TealLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JpanelTelaLogin = new javax.swing.JPanel();
        jLabeluser = new javax.swing.JLabel();
        jButtonEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelTituloEmail = new javax.swing.JLabel();
        jLabelTtuloSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelTituloTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JpanelTelaLogin.setBackground(new java.awt.Color(0, 102, 153));
        JpanelTelaLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabeluser.setBackground(new java.awt.Color(255, 51, 51));
        jLabeluser.setForeground(new java.awt.Color(255, 102, 102));
        jLabeluser.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jhonatans\\Desktop\\Imagens\\user.PNG")); // NOI18N
        JpanelTelaLogin.add(jLabeluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 20, 20));

        jButtonEntrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        JpanelTelaLogin.add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 263, 36));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jhonatans\\Desktop\\Imagens\\cade.PNG")); // NOI18N
        JpanelTelaLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 30, 20));

        jTextFieldLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginActionPerformed(evt);
            }
        });
        JpanelTelaLogin.add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 213, 33));

        jLabelTituloEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelTituloEmail.setForeground(new java.awt.Color(245, 255, 250));
        jLabelTituloEmail.setText("Usuario*");
        JpanelTelaLogin.add(jLabelTituloEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabelTtuloSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelTtuloSenha.setForeground(new java.awt.Color(245, 255, 250));
        jLabelTtuloSenha.setText("Senha*");
        JpanelTelaLogin.add(jLabelTtuloSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jPasswordFieldSenha.setActionCommand("<Not Set>");
        JpanelTelaLogin.add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 213, 34));

        jLabelTituloTela.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabelTituloTela.setForeground(new java.awt.Color(245, 255, 250));
        jLabelTituloTela.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jhonatans\\Desktop\\Imagens\\logoFinal.PNG")); // NOI18N
        JpanelTelaLogin.add(jLabelTituloTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 170, 40));

        getContentPane().add(JpanelTelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        
        String login = jTextFieldLogin.getText(); // Obtendo login digitado
        String senha = new String(jPasswordFieldSenha.getPassword()); // Obtendo senha digitada
        
        try {
            Usuario usuario = new Usuario(login, senha); // Construtor
            DAO dao = new DAO();
            if (dao.existeUsuario(usuario)) { // Verificando se existe o usuario
                if (dao.existeAtendente(usuario) == true) { // Autenticando o usario para a tela
                    TelaMenuAdmin menuAdmin = new TelaMenuAdmin();
                    menuAdmin.setVisible(true);
                    this.dispose();
                } else {
                    MenuAtendente menuAtendente = new MenuAtendente();
                    menuAtendente.setVisible(true);
                    this.dispose();
                }
            // Caso não exista usuario
            } else {
                JOptionPane.showMessageDialog(null, "Usuario não cadastrado!");
            }
        }
        catch (Exception e ) {
            JOptionPane.showMessageDialog(null, "Falha na conexão, chame o suporte");
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TealLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TealLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TealLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TealLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TealLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpanelTelaLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTituloEmail;
    private javax.swing.JLabel jLabelTituloTela;
    private javax.swing.JLabel jLabelTtuloSenha;
    private javax.swing.JLabel jLabeluser;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
